// components/Content.vue
<template lang="pug">
  section
    .container
      .flex.w-full(:class="classe")
        slot
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  name: 'Content',
  props: {
    classe: {
      type: String,
      default: ''
    }
  }
})
</script>

<style lang="sass" scoped>
section
  min-height: calc(100vh - 85px)
  display: flex
  justify-content: center
  align-items: center
</style>

// src/lib/Content.svelte
<script lang="ts">
	export let classe: string = '';
</script>

<section>
	<div class="container">
		<div class={`flex w-full ${classe}`}>
			<slot />
		</div>
	</div>
</section>

<style lang="sass">
section
  min-height: calc(100vh - 85px)
  display: flex
  justify-content: center
  align-items: center
</style>
